# Generated by Django 5.2.11 on 2026-02-17 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
                ('court_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('choice', models.CharField(blank=True, choices=[('DEFENCE', 'Defence'), ('CHASE', 'Chase')], max_length=10, null=True)),
                ('result_margin', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('officials', models.JSONField(blank=True, default=dict, help_text='Scorer, Umpires, Referee, Timekeeper')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('chest_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('coach', models.CharField(blank=True, max_length=255, null=True)),
                ('manager', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('organizer', models.CharField(help_text='e.g., Maharashtra Kho Kho Association', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning_number', models.IntegerField(help_text='1, 2, 3, 4')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='core.match')),
                ('chasing_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings_chasing', to='core.team')),
                ('defending_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings_defending', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='e.g., SIMPLE_TOUCH, DIVE, LATE_ENTRY', max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('timestamp', models.TimeField(blank=True, help_text='Run time', null=True)),
                ('symbol', models.CharField(blank=True, help_text='S, L, O, etc.', max_length=10, null=True)),
                ('defender_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_events_as_defender', to='core.player')),
                ('inning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='core.inning')),
                ('raider_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_events_as_raider', to='core.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_a', to='core.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_b', to='core.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='toss_won_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_toss_won', to='core.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='core.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.tournament'),
        ),
    ]
