# Generated by Django 5.2.7 on 2026-03-16 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='start_date',
        ),
    ]
