# Generated by Codex on 2026-03-24

from django.db import migrations, models


def _diff_payload(base, candidate):
    if isinstance(base, dict) and isinstance(candidate, dict):
        diff = {}
        for key, candidate_value in candidate.items():
            base_value = base.get(key)
            nested_diff = _diff_payload(base_value, candidate_value)
            if nested_diff is not None:
                diff[key] = nested_diff
        return diff or None

    if isinstance(base, list) and isinstance(candidate, list):
        return candidate if candidate != base else None

    return candidate if candidate != base else None


def backfill_layers(apps, schema_editor):
    ExtractedData = apps.get_model("core", "ExtractedData")
    ReviewedData = apps.get_model("core", "ReviewedData")

    extracted_by_request = {}

    for extracted in ExtractedData.objects.all().iterator():
        stored_payload = extracted.raw_payload or {}
        raw_ocr = stored_payload if isinstance(stored_payload, dict) else {}
        extracted_payload = {}

        if isinstance(stored_payload, dict):
            if isinstance(stored_payload.get("raw_ocr"), dict):
                raw_ocr = stored_payload.get("raw_ocr") or {}

            if isinstance(stored_payload.get("extracted"), dict):
                extracted_payload = stored_payload.get("extracted") or {}
            else:
                extracted_payload = {
                    key: stored_payload.get(key)
                    for key in ("match_info", "teams", "score", "officials", "remarks")
                    if key in stored_payload
                }

        extracted.raw_payload = raw_ocr if isinstance(raw_ocr, dict) else {}
        extracted.extracted_payload = extracted_payload if isinstance(extracted_payload, dict) else {}
        extracted.save(update_fields=["raw_payload", "extracted_payload"])
        extracted_by_request[str(extracted.request_id)] = extracted.extracted_payload

    for reviewed in ReviewedData.objects.all().iterator():
        base_payload = extracted_by_request.get(str(reviewed.request_id), {})
        final_payload = reviewed.final_payload or {}
        reviewed.user_edits = _diff_payload(base_payload, final_payload) or {}
        reviewed.save(update_fields=["user_edits"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_uploadrequest_revieweddata_extracteddata_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="extracteddata",
            name="extracted_payload",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="revieweddata",
            name="user_edits",
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(backfill_layers, migrations.RunPython.noop),
    ]
