# Generated by Django 5.2.7 on 2026-03-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_tournament_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='city',
        ),
        migrations.AddField(
            model_name='team',
            name='supporting_staff',
            field=models.JSONField(blank=True, default=list, help_text='List of other staff objects/strings', null=True),
        ),
    ]
