# Generated by Django 5.2.11 on 2026-03-24 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_extracted_layers_and_user_edits'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='sheet_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Full submitted scoresheet payload from OCR review flow'),
        ),
        migrations.AddField(
            model_name='match',
            name='source_upload_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_matches', to='core.uploadrequest'),
        ),
    ]
