# Generated by Django 5.2.7 on 2026-03-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_team_city_team_supporting_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='supporting_staff',
            field=models.CharField(blank=True, help_text='Supporting staff names/roles', max_length=255, null=True),
        ),
    ]
