# Generated by Django 5.2.7 on 2026-03-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_team_supporting_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_no', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('court_no', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('toss_winner', models.CharField(max_length=100)),
                ('choice', models.CharField(max_length=100)),
            ],
        ),
    ]
