# Generated by Django 5.2.7 on 2026-03-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_matchdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scorer_1', models.CharField(max_length=255)),
                ('scorer_2', models.CharField(max_length=255)),
                ('umpire_1', models.CharField(max_length=255)),
                ('umpire_2', models.CharField(max_length=255)),
                ('post_umpire_1', models.CharField(blank=True, max_length=255, null=True)),
                ('post_umpire_2', models.CharField(blank=True, max_length=255, null=True)),
                ('dugout', models.CharField(blank=True, max_length=255, null=True)),
                ('timekeeper', models.CharField(max_length=255)),
                ('referee', models.CharField(max_length=255)),
            ],
        ),
    ]
