# Generated by Django 5.2.7 on 2026-03-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_matchstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a_name', models.CharField(max_length=255)),
                ('team_b_name', models.CharField(max_length=255)),
                ('team_a_total', models.IntegerField()),
                ('team_b_total', models.IntegerField()),
            ],
        ),
    ]
