# Generated by Django 5.2.7 on 2026-03-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_matchresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_entry', models.JSONField(blank=True, default=list)),
                ('out_of_field', models.JSONField(blank=True, default=list)),
                ('warning', models.JSONField(blank=True, default=list)),
                ('dream_run', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
