# Generated by Django 5.2.7 on 2026-03-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_extrapoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('I', models.JSONField(blank=True, default=list)),
                ('II', models.JSONField(blank=True, default=list)),
                ('III', models.JSONField(blank=True, default=list)),
                ('IV', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
