# Generated by Django 5.2.7 on 2026-03-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_substitution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substitution',
            name='subs',
        ),
        migrations.AddField(
            model_name='substitution',
            name='player_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='substitution',
            name='player_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='substitution',
            name='team',
            field=models.CharField(choices=[('A', 'Team A'), ('B', 'Team B')], default='A', max_length=1),
        ),
    ]
