# Generated by Django 5.2.7 on 2026-03-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_substitution_subs_substitution_player_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdetails',
            name='batches',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
