# Generated by Django 5.2.7 on 2026-03-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_defence'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='team_A',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='team_B',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
