# Generated by Django 5.2.7 on 2026-03-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_matchresult_team_a_matchresult_team_b'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
