# Generated by Django 5.2.7 on 2026-03-16 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_scorecard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreevent',
            name='inning',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_a',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_b',
        ),
        migrations.RemoveField(
            model_name='match',
            name='toss_won_by',
        ),
        migrations.RemoveField(
            model_name='match',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='scoreevent',
            name='defender_player',
        ),
        migrations.RemoveField(
            model_name='scoreevent',
            name='raider_player',
        ),
        migrations.DeleteModel(
            name='Inning',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='ScoreEvent',
        ),
    ]
