# Generated by Django 5.2.7 on 2026-03-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_scoreevent_inning_remove_match_team_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdetails',
            name='tournamentId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
