# Generated by Django 5.2.7 on 2026-03-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_matchdetails_tournamentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substitution',
            name='player_in',
        ),
        migrations.RemoveField(
            model_name='substitution',
            name='player_out',
        ),
        migrations.RemoveField(
            model_name='substitution',
            name='team',
        ),
        migrations.AddField(
            model_name='substitution',
            name='Substitutions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
