# Generated by Django 5.2.7 on 2026-03-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_substitution_player_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorecard',
            name='events',
        ),
        migrations.AddField(
            model_name='scorecard',
            name='Team_A',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='Team_B',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
