# Generated by Django 5.2.7 on 2026-03-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_runningbatch_i_remove_runningbatch_ii_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrapoints',
            name='dream_run',
        ),
        migrations.RemoveField(
            model_name='extrapoints',
            name='late_entry',
        ),
        migrations.RemoveField(
            model_name='extrapoints',
            name='out_of_field',
        ),
        migrations.RemoveField(
            model_name='extrapoints',
            name='warning',
        ),
        migrations.AddField(
            model_name='extrapoints',
            name='Team_A',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='extrapoints',
            name='Team_B',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
