# Generated by Django 5.2.7 on 2026-03-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_extrapoints_dream_run_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chase',
            name='I',
        ),
        migrations.RemoveField(
            model_name='chase',
            name='II',
        ),
        migrations.RemoveField(
            model_name='chase',
            name='III',
        ),
        migrations.RemoveField(
            model_name='chase',
            name='IV',
        ),
        migrations.AddField(
            model_name='chase',
            name='Team_A',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chase',
            name='Team_B',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
