# Generated by Django 5.2.7 on 2026-03-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_chase_i_remove_chase_ii_remove_chase_iii_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defence',
            name='I',
        ),
        migrations.RemoveField(
            model_name='defence',
            name='II',
        ),
        migrations.RemoveField(
            model_name='defence',
            name='III',
        ),
        migrations.RemoveField(
            model_name='defence',
            name='IV',
        ),
        migrations.AddField(
            model_name='defence',
            name='Team_A',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='defence',
            name='Team_B',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
