# Generated by Django 5.2.7 on 2026-03-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_defence_i_remove_defence_ii_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdetails',
            name='teamB_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchdetails',
            name='team_A_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
