# Generated by Django 5.2.7 on 2026-03-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_matchdetails_teamb_id_matchdetails_team_a_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chase',
            name='match_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defence',
            name='match_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extrapoints',
            name='match_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='match_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstaff',
            name='match_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runningbatch',
            name='match_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='match_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='substitution',
            name='match_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='match_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
