from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from django.db import models

def generate_scoresheet_pdf(match):
    """
    Generates a PDF scoresheet for the given match.
    Returns a BytesIO buffer containing the PDF.
    """
    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    
    # Title
    p.setFont("Helvetica-Bold", 16)
    p.drawCentredString(width / 2, height - 50, "KHO KHO SCORE SHEET")
    
    # Match Details Header
    p.setFont("Helvetica-Bold", 12)
    y = height - 80
    p.drawString(50, y, f"Match No: {match.match_number}")
    p.drawRightString(width - 50, y, f"Date: {match.date}  Time: {match.time}")
    
    y -= 20
    p.setFont("Helvetica", 11)
    p.drawString(50, y, f"Tournament: {match.tournament.name if match.tournament else 'N/A'}")
    p.drawRightString(width - 50, y, f"Venue: {match.tournament.venue if match.tournament else 'N/A'}")
    
    # Teams & Toss
    y -= 40
    p.setFont("Helvetica-Bold", 12)
    p.drawString(50, y, f"TEAM A: {match.team_a.name}")
    p.drawRightString(width - 50, y, f"TEAM B: {match.team_b.name}")
    
    y -= 25
    p.setFont("Helvetica", 11)
    p.drawString(50, y, f"Toss Won By: {match.toss_won_by.name if match.toss_won_by else 'N/A'}")
    p.drawRightString(width - 50, y, f"Choice: {match.choice or 'N/A'}")
    
    # Officials
    y -= 40
    p.setFont("Helvetica-Bold", 11)
    p.drawString(50, y, "OFFICIALS:")
    y -= 20
    p.setFont("Helvetica", 10)
    officials = match.officials or {}
    off_text = ", ".join([f"{k}: {v}" for k, v in officials.items() if v])
    if off_text:
        p.drawString(50, y, off_text)
    else:
        p.drawString(50, y, "Scorer, Umpires, Referee, Timekeeper (Not specified)")

    # Scores Table Header
    y -= 40
    p.setFont("Helvetica-Bold", 12)
    p.drawString(50, y, "MATCH SCORES")
    p.line(50, y - 5, width - 50, y - 5)
    
    y -= 25
    p.setFont("Helvetica-Bold", 10)
    p.drawString(60, y, "Inning")
    p.drawString(120, y, "Chasing Team")
    p.drawString(300, y, "Defending Team")
    p.drawRightString(width - 60, y, "Points")
    
    y -= 20
    p.setFont("Helvetica", 10)
    
    innings = match.innings.all().order_by('inning_number')
    for inning in innings:
        chasing = inning.chasing_team.name
        defending = inning.defending_team.name
        score = inning.score_events.aggregate(total_points=models.Sum('points'))['total_points'] or 0
        
        p.drawString(60, y, f"{inning.inning_number}")
        p.drawString(120, y, f"{chasing}")
        p.drawString(300, y, f"{defending}")
        p.drawRightString(width - 60, y, f"{score}")
        y -= 15

    # Result
    y -= 30
    p.setFont("Helvetica-Bold", 12)
    winner_name = match.winner.name if match.winner else "Pending"
    p.drawString(50, y, f"WINNER: {winner_name}")
    if match.result_margin:
        p.drawRightString(width - 50, y, f"Result Details: {match.result_margin}")

    # Footer
    p.setFont("Helvetica-Oblique", 8)
    p.drawCentredString(width / 2, 30, "Generated by Kho Kho Score System API")
    
    p.showPage()
    p.save()
    
    buffer.seek(0)
    return buffer
